version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-serialization-json"
      - dependency-name: "org.jetbrains.kotlin:kotlin-stdlib"
    groups:
      junit-jupiter:
        patterns:
          - "org.junit.jupiter:*"
          - "org.junit.platform:*"
