name: Rebase Dependabot stale PRs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  rebase-dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: "Rebase open Dependabot PR"
      uses: orange-buffalo/dependabot-auto-rebase@v1
      with:
        api-token: ${{ secrets.DEPENDABOT_ACTIONS_TOKEN }}
        repository: ${{ github.repository }}
